### PR TITLE
Split webview JS into separate file

### PR DESCRIPTION
**Pull request by ianjsikes**
- move the JS from the script tag into its own file
- instead of pasting the state into the JS directly, fire a "ready" event from the webview to signal when it is ready to receive data
- implement a basic templating function to help import scripts into the webview html

I figured this change will make it easier to expand on the webview JS in the future. The diff for the `graph.js` file is a little annoying, but the only change from where it was in the script tag is this line at the very bottom:
```js
vscode.postMessage({ type: "ready" });
```

### CODE REVIEW

**Comment by tchayen** [comment]
Thanks a lot! I am sorry for not coming back to you sooner.

Can I ask you for one more thing? Could you please check it with current master if all changes are applied properly? I don't think there would be an issue but I'd like to avoid potential problems with that. As soon as we know that code is in sync I can merge it 😄.

**Comment by ianjsikes** [comment]
@tchayen it looks good to go. There are a couple of duplicate changes from @ingalless 's PR, but they seem to be formatting stuff. I'm guessing that we both have Prettier installed and it autoformatted `extension.ts`

**Comment by ingalless** [comment]
@ianjsikes that will be precisely what those are! Probably a prettier 1.x defaults Vs 2.x defaults thing

**Comment by tchayen** [comment]
Ok then. I should definitely set up a CI for checking those at some point 😅 .

**Pull request merged**
