### PR TITLE
Add a setting to cut titles after a certain length

### PR DESCRIPTION
**Pull request by jmg-duarte**
This PR is directly related to #66 

The idea is to simple cut/abbreviate long titles by setting a limit (current default is 24) and after the limit append ...

### CODE REVIEW

**Review by ingalless — COMMENTED** [review]
Code looks good! Nice work.
I think I'd like to see a way to disable this. What do you think? Sure, you could set the limit to 1000 and that would do it...

**Comment by jmg-duarte** [comment]
I thought of that, set the limit to 0 or negative and it won't cut

**Comment by jmg-duarte** [comment]
I just pushed a new commit to include instructions on how to disable

**Review by ingalless — APPROVED** [review]
Looks good to me! @tchayen any further thoughts?

**Comment by jmg-duarte** [comment]
I noticed the README lacked the documentation for the new configuration so I added it meanwhile

**Comment by tchayen** [comment]
Thanks a lot for this PR!

I am merging it. I will try to release it sooner than later, I think I got some other fixes to push too that I forgot about 😬 .

**Pull request merged**
