### PR TITLE
scale label with node size

### PR DESCRIPTION
**Pull request by Am3ra**

### CODE REVIEW

**Comment by Am3ra** [comment]
Resolves #57

**Comment by ingalless** [comment]
Good work!

This doesn't appear to base the scaling by the editor font size, as was floated as a suggestion in the issue. Is this something you feel comfortable investigating?

**Comment by Am3ra** [comment]
> Good work!
> 
> This doesn't appear to base the scaling by the editor font size, as was floated as a suggestion in the issue. Is this something you feel comfortable investigating?

I did investigate it, let me post the results: 

Using `nodeSize[d.id]` 

Screen Shot 2020-09-19 at 17 23 54

Using `nodeSize[d.id]* editor.fontSize`

Screen Shot 2020-09-20 at 14 34 11

I also tried other scaling parameters such as `nodeSize[d.id]* editor.fontSize / 8` but there didn't seem to be any meaningful change to the basic settings. 

Regarding scaling by `editor.fontSize`, I didn't see the benefit. When using it to scale the size of the label, in almost every test, there wasn't much difference in sizes between nodes, and then as a bonus, sometimes ran into the positioning problem.

Using only `nodeSize[d.id]` had the benefit of not really messing with the positioning, as well as having a good range of sizes between nodes.

(As an aside, there is quite a bit of code devoted to making sure the node sizes are within a certain range and distribution, so taking advantage of the node sizes seemed to be a rather simple and effective solution that I didn't expect. I was expecting a lot more work!)

**Comment by ingalless** [comment]
Hmm yeah, I see the result is a little bizarre

The true benefit is accessibility. Someone hard of sight shouldn't have to constantly be super zoomed in when they're able to increase the size of their code already. But, perhaps it can be considered a future improvement. Good work nonetheless! And thanks for the investigation work too

**Comment by tchayen** [comment]
@Am3ra maybe I misread some crucial part here but isn't it possible to use `editor.fontSize` as baseline and then add on top of that based on nodeSize?

**Comment by Am3ra** [comment]
@tchayen, sorry I didn't include images of those tests, here they are:

using `nodeSize[d.id] + editor.fontSize`

Screen Shot 2020-09-21 at 16 21 01

Using `nodeSize[d.id]/4 + editor.fontSize`

Screen Shot 2020-09-21 at 16 24 27


I tried many other scalings, between 1 and around 10 but seemed to run into the same problem. While in theory this is possibly to correct by changing the label position, there doesn't seem to be a real benefit to using `editor.fontSize`, considering it's trivial to zoom in. Additionally, `editor.fontSize` reduces de range of possible values: in every test I did, the difference in font size between the smallest and largest node was not noticeable.

Finally, using `editor.fontSize` has the issue that at large font sizes, the labels of the nodes seem to overlap as well as covering the nodes themselves, requiring more space between nodes, effectively just zooming out the graph, defeating the purpose.

@tchayen @ingalless , do you have any other possible combinations y could test? I want to be as thorough as possible. 

Anyways, just wanted to say, @tchayen , @ingalless , both of you have been extremely helpful throughout this process, I really appreciate all you've done to smooth it out!

**Comment by Am3ra** [comment]
As an aside, something I just discovered is that text size **_does_** change with editor zoom, see here how the zoom of the graph is the same in all cases, but the size of labels changes:

Screen Shot 2020-09-21 at 16 40 42

Screen Shot 2020-09-21 at 16 40 54

**Comment by tchayen** [comment]
Yea, you can check the code of zoom adjustment function. There is some scaling done which (at least at the beginning when I wrote it, but it is probably different for the obsidian view) is meant to make text appear in the same size with scaling until some threshold and then raise (you a function zoom -> size is a constant value which turns into a linear function at some point).

If this is relevant in any way to the obsidian view then it should be possible to use it to adjust scaling accordingly.

To be honest I have no clear idea of what the problem is here judging by the screenshots and formulas you have sent so I am giving those suggestions mostly blindly.

**Comment by Am3ra** [comment]
@tchayen , What would you say is missing to merge this PR? The graph already scales with editor font size.

**Comment by tchayen** [comment]
Ok, sorry for making it take longer than it should. Merging!

I will check what else happened recently and probably aim to release it some time soon (ping me please if I don't).

**Comment by Am3ra** [comment]
Thanks @tchayen , don't worry about the wait!

Again, thanks @tchayen and @ingalless for your help in this process. It's one of my first times contributing to open source, and you made it painless.

**Comment by ingalless** [comment]
@Am3ra great work! Thank you for this contribution, it's great! Looking forward to using it Monday ☺️

**Comment by tchayen** [comment]
@Am3ra Thanks again! If you ever think about fixing some problems with Markdown Links, feel free to open an issue or a draft PR if you don't have the full idea of the solution yet and I will be very happy to help any time.

**Pull request merged**
